version: '2'
services:
    app:
        build: docker/php
        volumes:
            - ./app:/app
    server:
        build: docker/nginx
        ports:
            - "80:80"
        volumes_from:
            - app
    db:
        image: mysql:5.7.16
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/mysql/:/docker-entrypoint-initdb.d
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
